"""FastAPI surface for the TradingAgents graph.

Routes
------

* ``POST /analyze`` — submit a job (returns immediately with ``{job_id}``)
* ``GET  /analyze/{job_id}`` — poll status; result populated when ``status="done"``
* ``GET  /healthz`` — liveness probe (Render hits this)
* ``GET  /openapi.json`` — auto-generated spec; the teammate's LLM imports it

Auth
----
All endpoints except ``/healthz`` and ``/openapi.json`` require an
``X-API-Key`` header matching the ``TRADINGAGENTS_API_KEY`` env var.
The key is generated by you (e.g. ``openssl rand -hex 32``) and shared
out-of-band with the teammate.
"""

from __future__ import annotations

import os
from typing import Any, Optional

from fastapi import Depends, FastAPI, HTTPException, status
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, Field

from server.jobs import get_job, submit_job

app = FastAPI(
    title="TradingAgents API",
    version="1.0.0",
    description=(
        "Run the multi-agent trading-analysis graph over HTTP. "
        "Submit a ticker + trade date to /analyze, poll /analyze/{job_id} "
        "until status='done', then read the structured analyst reports "
        "and final decision from the result field."
    ),
)


# --- Auth -------------------------------------------------------------------

# auto_error=False so we can return our own 401 with a helpful detail
# message instead of FastAPI's generic "Not authenticated".
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def require_api_key(x_api_key: Optional[str] = Depends(_api_key_header)) -> None:
    """Validate the ``X-API-Key`` header against the configured shared secret.

    Fail closed: if the env var isn't set the server refuses every request,
    so a misconfigured deploy can't accidentally be fully open.
    """
    expected = os.environ.get("TRADINGAGENTS_API_KEY")
    if not expected:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Server is missing TRADINGAGENTS_API_KEY",
        )
    if not x_api_key or x_api_key != expected:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing X-API-Key header",
        )


# --- Schemas ----------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    ticker: str = Field(
        ...,
        examples=["AAPL", "002594.SZ", "600519.SS"],
        description="Yahoo-style ticker. Chinese A-shares use .SS / .SZ suffixes.",
    )
    trade_date: str = Field(
        ...,
        examples=["2026-06-19"],
        description="ISO date the analysis is anchored on (YYYY-MM-DD).",
    )
    asset_type: str = Field(
        default="stock",
        examples=["stock", "crypto"],
        description="'stock' uses the equity pipeline; 'crypto' uses the crypto pipeline.",
    )
    selected_analysts: Optional[list[str]] = Field(
        default=None,
        examples=[["market", "social", "news", "fundamentals"]],
        description=(
            "Subset of analysts to run. Defaults to all four. "
            "Trim to shorten run time."
        ),
    )


class AnalyzeSubmitted(BaseModel):
    job_id: str
    status: str


class AnalyzeStatus(BaseModel):
    id: str
    status: str
    ticker: str
    trade_date: str
    asset_type: str
    selected_analysts: list[str]
    submitted_at: float
    started_at: Optional[float] = None
    finished_at: Optional[float] = None
    result: Optional[dict[str, Any]] = None
    signal: Optional[Any] = None
    error: Optional[str] = None


# --- Routes -----------------------------------------------------------------

@app.get("/healthz", tags=["meta"])
def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.post(
    "/analyze",
    response_model=AnalyzeSubmitted,
    dependencies=[Depends(require_api_key)],
    tags=["analyze"],
)
async def analyze(req: AnalyzeRequest) -> AnalyzeSubmitted:
    """Submit a new analysis job. Returns ``{job_id, status}`` immediately.

    ``async`` is required so ``submit_job`` sees a running event loop for
    ``asyncio.create_task``; a sync handler would run in the threadpool.
    """
    job = submit_job(
        ticker=req.ticker,
        trade_date=req.trade_date,
        asset_type=req.asset_type,
        selected_analysts=req.selected_analysts,
    )
    return AnalyzeSubmitted(job_id=job.id, status=job.status)


@app.get(
    "/analyze/{job_id}",
    response_model=AnalyzeStatus,
    dependencies=[Depends(require_api_key)],
    tags=["analyze"],
)
def analyze_status(job_id: str) -> AnalyzeStatus:
    """Return current status (and the result, once ``status='done'``)."""
    job = get_job(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail=f"Unknown job_id: {job_id}")
    return AnalyzeStatus(**job.public_dict())
